### PR TITLE
Update docs to Docusaurus v3

### PR DESCRIPTION
**Pull request by MatthewL246**
This was a bit of a complicated update but I think this will work.

### CODE REVIEW

**Comment by MatthewL246** [comment]
Well, the top header is broken. That needs to be fixed.

**Comment by MatthewL246** [comment]
I'm not familliar with React, so I'm going to need some help with this.

**Comment by MatthewL246** [comment]
And now the breadcrumbs are gone

**Comment by MatthewL246** [comment]
Basically, I removed most of the custom React components to update this to Docusaurus v3. I think it still looks fine but I'd appreciate your feedback (specifically any CSS tweaks that would make it look better).

**Review by michaell4438 — APPROVED** [review]
if it works it works. Lgtm

**Comment by MatthewL246** [comment]
Old Docusaurus v2 site is archived at https://github.com/XaverianTeamRobotics/docs/tree/archive-docusaurus-v2.

**Pull request merged**
